### ISSUE TITLE
How long does the training take to achieve a comparable result compared with the paper results?

### ISSUE THREAD

**Issue by shiyi001** [Duankaiwen/CenterNet#2]
Can you provide training time in a configuration(including training environment and network configuration)? Cause it takes a long time to achieve a good result for CornerNet.

https://github.com/princeton-vl/CornerNet/issues/67

Many Thanks.

**Comment by Duankaiwen** [comment]
It takes about 2-3 weeks to train. We train the CenterNet on 8 Tesla V100 (32GB) GPUs and use a batch size of 48. We use the max batch size as we can, because we want to make full use of the memory. The network configuration is similar to CornerNet. If you want to speed up the training time, you may try reducing the batch size and the channels. We are not sure how much worse the result will be with the smaller batch size.

**Comment by Duankaiwen** [comment]
Or try using the trained model of CornerNet as the pre-trained model
